title: "Blogs"
email: hernan@hernangarciaval.com
timezone: "America/Peru" 
baseurl: "/blog"
permalink: ":year/:month/:day/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Hernán
paginate: 15
# disqus: 'https-www-hernangarciaval-me-blog'
locale: es_es
lang: es_es
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-SPNXNSGBGK

# Authors
authors:
  kaustubh:
    name: Hernan Garcia
    display_name: Hernán
    avatar: 'assets/images/avatar-hernan.png'
    email: hernan@hernangarciaval.com
    web: https://www.hernangarciaval.com
    twitter: https://twitter.com/hernangarciaval
    description: "Consultor simpático selectivo"

# Social
social:
  twitter: https://twitter.com/hernangarciaval
  github: https://github.com/kanancho
  linkedin: https://www.linkedin.com/in/hernangarciavaldeavellano

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
