title: "Blogs"
email: kaustubhgupta1828@gmail.com
timezone: "Asia/Kolkata" 
baseurl: ""
permalink: ":year/:month/:day/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: kaustubh
paginate: 10
disqus: 'https-www-kaustubhgupta-me-blog'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-WKWMZE48XH

# Authors
authors:
  kaustubh:
    name: Kaustubh Gupta
    display_name: Kaustubh Gupta
    avatar: 'assets/images/profile_pic.jpg'
    email: kaustubhgupta1828@gmail.com
    web: https://www.kaustubhgupta.me
    twitter: https://twitter.com/Kaustubh1828
    description: "That Data Guy, Habitual Writer and Tech Enuthusist"

# Social
social:
  twitter: https://twitter.com/Kaustubh1828
  github: https://github.com/kaustubhgupta
  linkedin: https://www.linkedin.com/in/kaustubh-gupta
  medium: https://medium.com/@kaustubhgupta1828

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
